// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// method_contiguous
LogicalVector method_contiguous(NumericMatrix xy, int center, double step_x, double step_y, double target);
RcppExport SEXP _spatialFolds_method_contiguous(SEXP xySEXP, SEXP centerSEXP, SEXP step_xSEXP, SEXP step_ySEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xy(xySEXP);
    Rcpp::traits::input_parameter< int >::type center(centerSEXP);
    Rcpp::traits::input_parameter< double >::type step_x(step_xSEXP);
    Rcpp::traits::input_parameter< double >::type step_y(step_ySEXP);
    Rcpp::traits::input_parameter< double >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(method_contiguous(xy, center, step_x, step_y, target));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spatialFolds_method_contiguous", (DL_FUNC) &_spatialFolds_method_contiguous, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_spatialFolds(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
