# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' (C++) Generate Training Fold Using Binary Search (Rectangle-Preserving)
#' @description Optimized implementation using binary search to find rectangle dimensions. Maintains rectangle shape and uses step_x/step_y parameters while achieving significant speedup (15-20x) through reduced iterations.
#' @param xy (required, numeric matrix) Two columns matrix with the locations to arrange. The first column is interpreted as "x" (longitude) and the second as "y" (latitude). Default: `NULL`
#' @param center (required, integer) Index of the training fold center (1-based indexing as in R). Default: `NULL`
#' @param step_x (required, numeric) Rectangle growth increment along the x-axis. Must be in the same units as `xy`. Default: `NULL`
#' @param step_y (required, numeric) Rectangle growth increment along the y-axis. Must be in the same units as `xy`. Default: `NULL`
#' @param target (optional, integer) Number of records to include in the training fold. Default: `NULL`.
#' @return logical vector with length equal to nrow(xy), where TRUE indicates a record is in the training fold and FALSE indicates it is in the testing fold.
#' @details
#' This function uses binary search to efficiently find the rectangle size:
#' \enumerate{
#'   \item Determines the maximum possible rectangle scale from data extent
#'   \item Binary searches for scale factor that yields target count
#'   \item Each iteration counts points in rectangle (O(n))
#'   \item Total iterations: O(log(max_scale)) typically 10-15
#'   \item Returns logical vector for final rectangle
#' }
#'
#' This maintains rectangle shape and produces similar results to the original
#' implementation while being much faster through reduced iterations.
#'
#' Complexity: O(n log iterations) where iterations ≈ 10-15
#' Performance: Typically 15-20x faster than R version on large datasets
#'
#' @examples
#' training <- training_fold_binary(
#'   xy = xy_matrix,
#'   center = 1,
#'   step_x = 0.4,
#'   step_y = 0.1,
#'   target = 15000
#' )
#'
#' training_fold_plot(
#'   xy = xy_matrix,
#'   center = 1,
#'   training_fold = training
#' )
#' @export
method_contiguous <- function(xy, center, step_x, step_y, target) {
    .Call(`_spatialFolds_method_contiguous`, xy, center, step_x, step_y, target)
}

