# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' (C++) Generate Blocks-Based Training Fold from Pre-computed Cell IDs
#' @description Randomly selects entire grid cells until target count reached. Cell assignments must be pre-computed in R via sf_to_grid().
#' @param xy (required, numeric matrix) Two columns matrix with locations. Used only for dimension checking (nrow must equal length of cell_id). Default: `NULL`
#' @param cell_id (required, integer vector) Pre-computed cell assignment for each point (0-based cell IDs from sf_to_grid()). Default: `NULL`
#' @param seed (required, integer) Random seed for reproducibility. Default: `NULL`
#' @param target (required, integer) Number of records to include in training fold. Default: `NULL`
#' @return logical vector with length equal to nrow(xy), where TRUE indicates training fold record
#' @details
#' Algorithm:
#' \enumerate{
#'   \item Count points per cell from cell_id vector (O(n) pass)
#'   \item Determine number of unique cells
#'   \item Shuffle cell IDs using Mersenne Twister RNG
#'   \item Select cells sequentially until cumulative count >= target
#'   \item Mark all points in selected cells as TRUE (O(n) pass)
#' }
#'
#' **Important**: Cell IDs must be pre-computed in R using sf_to_grid() before calling this function.
#' This optimization avoids recalculating cell assignments for each fold iteration.
#' For 1000 folds, this provides ~1.5x speedup by computing assignments once instead of 1000 times.
#'
#' Complexity: O(n + C log C) where C = number of unique cells
#' Memory: O(C) - minimal overhead
#'
#' @examples
#' # Cell IDs must be computed by sf_to_grid() in R first
#' cell_id <- sf_to_grid(xy_matrix, grid_rows = 10, grid_columns = 10)
#'
#' training <- method_blocks(
#'   xy = xy_matrix,
#'   cell_id = cell_id,
#'   seed = 123,
#'   target = 15000
#' )
#' @export
method_blocks <- function(xy, cell_id, seed, target) {
    .Call(`_spatialFolds_method_blocks`, xy, cell_id, seed, target)
}

#' (C++) Generate Contiguous Training Fold Using Binary Search
#' @description Optimized implementation using binary search to find rectangle dimensions. Maintains rectangle shape and uses step_x/step_y parameters while achieving significant speedup (15-20x) through reduced iterations.
#' @param xy (required, numeric matrix) Two columns matrix with the locations to arrange. The first column is interpreted as "x" (longitude) and the second as "y" (latitude). Default: `NULL`
#' @param center (required, integer) Index of the training fold center (1-based indexing as in R). Default: `NULL`
#' @param step_x (required, numeric) Rectangle growth increment along the x-axis. Must be in the same units as `xy`. Default: `NULL`
#' @param step_y (required, numeric) Rectangle growth increment along the y-axis. Must be in the same units as `xy`. Default: `NULL`
#' @param target (optional, integer) Number of records to include in the training fold. Default: `NULL`.
#' @return logical vector with length equal to nrow(xy), where TRUE indicates a record is in the training fold and FALSE indicates it is in the testing fold.
#' @details
#' This function uses binary search to efficiently find the rectangle size:
#' \enumerate{
#'   \item Determines the maximum possible rectangle scale from data extent
#'   \item Binary searches for scale factor that yields target count
#'   \item Each iteration counts points in rectangle (O(n))
#'   \item Total iterations: O(log(max_scale)) typically 10-15
#'   \item Returns logical vector for final rectangle
#' }
#'
#' This maintains rectangle shape and produces similar results to the original
#' implementation while being much faster through reduced iterations.
#'
#' Complexity: O(n log iterations) where iterations ≈ 10-15
#' Performance: Typically 15-20x faster than R version on large datasets
#'
#' @examples
#' training <- method_contiguous(
#'   xy = xy_matrix,
#'   center = 1, #first record in xy_matrix
#'   step_x = 0.4,
#'   step_y = 0.1,
#'   target = 15000
#' )
#'
#' spatial_fold_plot(
#'   xy = xy_matrix,
#'   center = 1, #first record in xy_matrix
#'   training_fold = training
#' )
#' @export
method_contiguous <- function(xy, center, step_x, step_y, target) {
    .Call(`_spatialFolds_method_contiguous`, xy, center, step_x, step_y, target)
}

#' (C++) Generate Random Training Fold
#' @description Randomly selects training samples without replacement until target count is reached.
#' @param xy (required, numeric matrix) Two columns matrix with the locations. The first column is interpreted as "x" (longitude) and the second as "y" (latitude). Default: `NULL`
#' @param seed (required, integer) Random seed for reproducibility. Default: `NULL`
#' @param target (required, integer) Number of records to include in the training fold. Default: `NULL`.
#' @return logical vector with length equal to nrow(xy), where TRUE indicates a record is in the training fold and FALSE indicates it is in the testing fold.
#' @details
#' This function implements random sampling without replacement:
#' \enumerate{
#'   \item Creates vector of all indices (0 to n-1)
#'   \item Sets random seed for reproducibility
#'   \item Shuffles indices using Fisher-Yates algorithm
#'   \item Marks first target indices as training samples (TRUE)
#'   \item Returns logical vector
#' }
#'
#' Complexity: O(n) for shuffling
#' Memory: O(n) for index vector
#'
#' @examples
#' training <- method_random(
#'   xy = xy_matrix,
#'   seed = 123,
#'   target = 15000
#' )
#' @export
method_random <- function(xy, seed, target) {
    .Call(`_spatialFolds_method_random`, xy, seed, target)
}

